"use client";

import { useState } from "react";
import { Package, Copy, Check, Code } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { useLocalStorage } from "@/lib/hooks";

interface AppConfig {
  appName: string;
  appSlug: string;
  scopes: string[];
  webhooks: string[];
  useTypescript: boolean;
  usePolaris: boolean;
  useAppBridge: boolean;
  apiVersion: string;
}

const AVAILABLE_SCOPES = [
  "read_products", "write_products", "read_orders", "write_orders",
  "read_customers", "write_customers", "read_inventory", "write_inventory",
  "read_content", "write_content", "read_themes", "write_themes",
  "read_shipping", "write_shipping", "read_analytics",
];

const AVAILABLE_WEBHOOKS = [
  "app/uninstalled", "orders/create", "orders/updated", "orders/paid",
  "products/create", "products/update", "products/delete",
  "customers/create", "customers/update", "carts/create", "carts/update",
  "inventory_levels/update", "themes/publish",
];

function generatePackageJson(config: AppConfig): string {
  return JSON.stringify({
    name: config.appSlug || "my-shopify-app",
    version: "1.0.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint",
    },
    dependencies: {
      "@shopify/shopify-api": "^9.0.0",
      ...(config.useAppBridge ? { "@shopify/app-bridge-react": "^4.0.0" } : {}),
      ...(config.usePolaris ? { "@shopify/polaris": "^12.0.0" } : {}),
      next: "^14.0.0",
      react: "^18.0.0",
      "react-dom": "^18.0.0",
    },
    devDependencies: {
      ...(config.useTypescript ? { typescript: "^5.0.0", "@types/react": "^18.0.0", "@types/node": "^20.0.0" } : {}),
      eslint: "^8.0.0",
      "eslint-config-next": "^14.0.0",
    },
  }, null, 2);
}

function generateEnvTemplate(config: AppConfig): string {
  return `# ${config.appName || "Shopify App"} Environment Variables
# Generated by App Config Generator

# Shopify App Credentials
SHOPIFY_API_KEY=your_api_key_here
SHOPIFY_API_SECRET=your_api_secret_here
SHOPIFY_APP_URL=https://your-app-url.com
SHOPIFY_API_VERSION=${config.apiVersion}

# Scopes
SCOPES=${config.scopes.join(",")}

# App Settings
HOST=https://your-app-url.com
PORT=3000
NODE_ENV=development

# Database (if needed)
DATABASE_URL=postgresql://localhost:5432/${config.appSlug || "shopify_app"}

# Session Storage
SESSION_STORAGE=memory
`;
}

function generateAuthConfig(config: AppConfig): string {
  const ext = config.useTypescript ? "ts" : "js";
  return `// auth.config.${ext}
// Shopify authentication configuration

${config.useTypescript ? `import { shopifyApi, ApiVersion, Session } from "@shopify/shopify-api";
import { restResources } from "@shopify/shopify-api/rest/admin/${config.apiVersion}";

` : ""}const shopify = shopifyApi({
  apiKey: process.env.SHOPIFY_API_KEY${config.useTypescript ? "!" : ""},
  apiSecretKey: process.env.SHOPIFY_API_SECRET${config.useTypescript ? "!" : ""},
  scopes: process.env.SCOPES${config.useTypescript ? "?.split(',')" : ".split(',')"},
  hostName: process.env.HOST${config.useTypescript ? "!" : ""},
  apiVersion: "${config.apiVersion}"${config.useTypescript ? " as ApiVersion" : ""},
  isEmbeddedApp: true,
  ${config.useTypescript ? "restResources," : ""}
});

// Webhook registrations
const WEBHOOKS = ${JSON.stringify(config.webhooks.reduce((acc, wh) => ({ ...acc, [wh]: { path: `/api/webhooks/${wh.replace(/\//g, "-")}` } }), {}), null, 2)};

export { shopify, WEBHOOKS };
`;
}

function generateReadme(config: AppConfig): string {
  return `# ${config.appName || "My Shopify App"}

## Setup

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Copy \`.env.example\` to \`.env\` and fill in your credentials:
\`\`\`bash
cp .env.example .env
\`\`\`

3. Run the development server:
\`\`\`bash
npm run dev
\`\`\`

## Configuration

- **API Version:** ${config.apiVersion}
- **Scopes:** ${config.scopes.join(", ") || "None configured"}
- **Webhooks:** ${config.webhooks.join(", ") || "None configured"}
- **TypeScript:** ${config.useTypescript ? "Yes" : "No"}
- **Polaris UI:** ${config.usePolaris ? "Yes" : "No"}
- **App Bridge:** ${config.useAppBridge ? "Yes" : "No"}

## Project Structure

\`\`\`
├── app/
│   ├── api/
│   │   ├── auth/
│   │   └── webhooks/
│   ├── layout.${config.useTypescript ? "tsx" : "jsx"}
│   └── page.${config.useTypescript ? "tsx" : "jsx"}
├── lib/
│   └── auth.config.${config.useTypescript ? "ts" : "js"}
├── .env.example
├── package.json
└── README.md
\`\`\`
`;
}

export default function AppBoilerplatePage() {
  const [config, setConfig] = useLocalStorage<AppConfig>("app-boilerplate-config", {
    appName: "",
    appSlug: "",
    scopes: ["read_products"],
    webhooks: ["app/uninstalled"],
    useTypescript: true,
    usePolaris: true,
    useAppBridge: true,
    apiVersion: "2024-01",
  });
  const [copiedFile, setCopiedFile] = useState<string | null>(null);

  function toggleScope(scope: string) {
    setConfig((prev) => ({
      ...prev,
      scopes: prev.scopes.includes(scope) ? prev.scopes.filter((s) => s !== scope) : [...prev.scopes, scope],
    }));
  }

  function toggleWebhook(wh: string) {
    setConfig((prev) => ({
      ...prev,
      webhooks: prev.webhooks.includes(wh) ? prev.webhooks.filter((w) => w !== wh) : [...prev.webhooks, wh],
    }));
  }

  function copyFile(name: string, content: string) {
    navigator.clipboard.writeText(content);
    setCopiedFile(name);
    setTimeout(() => setCopiedFile(null), 2000);
  }

  const files = [
    { name: "package.json", content: generatePackageJson(config) },
    { name: ".env.example", content: generateEnvTemplate(config) },
    { name: `auth.config.${config.useTypescript ? "ts" : "js"}`, content: generateAuthConfig(config) },
    { name: "README.md", content: generateReadme(config) },
  ];

  return (
    <div className="space-y-6">
      <PageHeader
        title="App Config Generator"
        description="Generate Shopify app boilerplate files: package.json, env, auth config, and README"
        icon={Package}
        badge="Shopify Ext"
        replaces="Manual scaffolding"
      />

      <div className="grid lg:grid-cols-2 gap-6">
        <div className="space-y-4">
          <Card>
            <CardHeader><CardTitle className="text-sm">App Settings</CardTitle></CardHeader>
            <CardContent className="space-y-3">
              <div className="space-y-1.5"><Label>App Name</Label><Input value={config.appName} onChange={(e) => setConfig((p) => ({ ...p, appName: e.target.value }))} placeholder="My Shopify App" /></div>
              <div className="space-y-1.5"><Label>Slug (package name)</Label><Input value={config.appSlug} onChange={(e) => setConfig((p) => ({ ...p, appSlug: e.target.value }))} placeholder="my-shopify-app" /></div>
              <div className="space-y-1.5"><Label>API Version</Label>
                <select className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm" value={config.apiVersion} onChange={(e) => setConfig((p) => ({ ...p, apiVersion: e.target.value }))}>
                  <option value="2024-10">2024-10</option><option value="2024-07">2024-07</option><option value="2024-04">2024-04</option><option value="2024-01">2024-01</option>
                </select>
              </div>
              <div className="flex items-center justify-between"><Label className="text-sm">TypeScript</Label><Switch checked={config.useTypescript} onCheckedChange={(c) => setConfig((p) => ({ ...p, useTypescript: c }))} /></div>
              <div className="flex items-center justify-between"><Label className="text-sm">Shopify Polaris</Label><Switch checked={config.usePolaris} onCheckedChange={(c) => setConfig((p) => ({ ...p, usePolaris: c }))} /></div>
              <div className="flex items-center justify-between"><Label className="text-sm">App Bridge</Label><Switch checked={config.useAppBridge} onCheckedChange={(c) => setConfig((p) => ({ ...p, useAppBridge: c }))} /></div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader><CardTitle className="text-sm">Scopes ({config.scopes.length})</CardTitle></CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-1.5">
                {AVAILABLE_SCOPES.map((scope) => (
                  <Badge key={scope} className={`cursor-pointer text-[10px] transition-colors ${config.scopes.includes(scope) ? "bg-violet-500/20 text-violet-600 border-violet-500/30" : "bg-muted text-muted-foreground border-0 hover:bg-muted/80"}`} onClick={() => toggleScope(scope)}>
                    {scope}
                  </Badge>
                ))}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader><CardTitle className="text-sm">Webhooks ({config.webhooks.length})</CardTitle></CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-1.5">
                {AVAILABLE_WEBHOOKS.map((wh) => (
                  <Badge key={wh} className={`cursor-pointer text-[10px] transition-colors ${config.webhooks.includes(wh) ? "bg-violet-500/20 text-violet-600 border-violet-500/30" : "bg-muted text-muted-foreground border-0 hover:bg-muted/80"}`} onClick={() => toggleWebhook(wh)}>
                    {wh}
                  </Badge>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-4">
          {files.map((file) => (
            <Card key={file.name}>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle className="text-sm flex items-center gap-2">
                    <Code className="h-3.5 w-3.5" /> {file.name}
                  </CardTitle>
                  <Button variant="outline" size="sm" onClick={() => copyFile(file.name, file.content)}>
                    {copiedFile === file.name ? <><Check className="h-3.5 w-3.5 mr-1" /> Copied</> : <><Copy className="h-3.5 w-3.5 mr-1" /> Copy</>}
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                <pre className="bg-muted/50 rounded-md p-3 text-[11px] overflow-x-auto font-mono whitespace-pre-wrap max-h-60 overflow-y-auto">{file.content}</pre>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
}
